spring:
  application:
    name: eureka-server
server:
  port: 9720

eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:9720/eureka/